version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/api
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: deploy/application-stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: deploy/before-install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy/after-install.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: deploy/application-start.sh
      timeout: 300
      runas: ec2-user
ValidateService:
  - location: deploy/validate.sh
    timeout: 60
    runas: ec2-user
